tasks:
  - name: Python Update Pip
    init: python -m pip install --upgrade pip
    command: pip install -r requirements.txt
  - name: Migrate app
    init: python manage.py Migrate
    command: python manage.py runserver

