# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Python Update Pip
    before:  python -m pip install --upgrade pip
    init: pip install -r requirements.txt

    command: echo 'start script'

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
#ports:
#  - name: Frontend
#    description: Port 3000 for the frontend
    #port: 000
#    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
